// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsZbfuR07OvCkJwRXeZFUJZiEnwJjVPPo',
    appId: '1:813710448691:web:33c0358fe3978b29272b46',
    messagingSenderId: '813710448691',
    projectId: 'timeguard-db233',
    authDomain: 'timeguard-db233.firebaseapp.com',
    storageBucket: 'timeguard-db233.firebasestorage.app',
    measurementId: 'G-PBS7LFZ5HT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP6WHSuFcT6PiBpur8xaZ4GkhnS2kZYa4',
    appId: '1:813710448691:android:3279ae5a387f37da272b46',
    messagingSenderId: '813710448691',
    projectId: 'timeguard-db233',
    storageBucket: 'timeguard-db233.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxzWCFu8x-U7bQ274PcaiRmiKRrkaQRyg',
    appId: '1:813710448691:ios:5c48c7da585caaa0272b46',
    messagingSenderId: '813710448691',
    projectId: 'timeguard-db233',
    storageBucket: 'timeguard-db233.firebasestorage.app',
    iosBundleId: 'com.example.timeguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxzWCFu8x-U7bQ274PcaiRmiKRrkaQRyg',
    appId: '1:813710448691:ios:5c48c7da585caaa0272b46',
    messagingSenderId: '813710448691',
    projectId: 'timeguard-db233',
    storageBucket: 'timeguard-db233.firebasestorage.app',
    iosBundleId: 'com.example.timeguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsZbfuR07OvCkJwRXeZFUJZiEnwJjVPPo',
    appId: '1:813710448691:web:31f5a78669692999272b46',
    messagingSenderId: '813710448691',
    projectId: 'timeguard-db233',
    authDomain: 'timeguard-db233.firebaseapp.com',
    storageBucket: 'timeguard-db233.firebasestorage.app',
    measurementId: 'G-0E073JJ4RJ',
  );
}
